### ISSUE TITLE
[2] First steps in installations [0$]

### ISSUE THREAD

**Issue by Vycraftujto** [FlameNET/FlameCMS#11]
I have problems in the first step of the installation. When I have all successfully uploaded to the FTP server my site and subsequently entered the web address into the browser jumped me this error. I was wondering whether there is no need to change the attributes but if so I do not know to what

Warning: session_start(): Cannot send session cookie - headers already sent by (output started at /data/web/virtuals/44875/virtual/www/subdom/wotlkptr/index.php:2) in /data/web/virtuals/44875/virtual/www/subdom/wotlkptr/system/config.php on line 28

Warning: session_start(): Cannot send session cache limiter - headers already sent (output started at /data/web/virtuals/44875/virtual/www/subdom/wotlkptr/index.php:2) in /data/web/virtuals/44875/virtual/www/subdom/wotlkptr/system/config.php on line 28

Warning: Cannot modify header information - headers already sent by (output started at /data/web/virtuals/44875/virtual/www/subdom/wotlkptr/index.php:2) in /data/web/virtuals/44875/virtual/www/subdom/wotlkptr/system/core.php on line 28

Warning: Cannot modify header information - headers already sent by (output started at /data/web/virtuals/44875/virtual/www/subdom/wotlkptr/index.php:2) in /data/web/virtuals/44875/virtual/www/subdom/wotlkptr/system/core.php on line 111

**Comment by oneluiz** [comment]
branch? 3.3.5? 4.3.4? 5.4.8? 6.x?

**Comment by Vycraftujto** [comment]
3.3.5

**Comment by FailZorD** [comment]
Excuse us but can you explain it more clearly?

If you can't write in english that perfectly, please write it on your own language and tell us what language you wrote your problem.

**Comment by Vycraftujto** [comment]
I apologize for the previous post.

My problem is with the installation website.
FlameCMS I downloaded from your site. Successful uploaded on my ftp. Then I wanted to open my website in the browser http://wotlkptr.vycraftujto.cz/ and after opening showed me the error.
I tried to delete htacces attached files because it may have a conflict with my original htacces file.
When I deleted the attached htacces, my web page through out the mistake that I mentioned at the beginning

**Comment by FailZorD** [comment]
That is really strange it must be your host. We've tested this in many servers and we never had any problems like that. Try on localhost and then on another server and let us know. :)

**Comment by Vycraftujto** [comment]
So, instead of finding a solution to this problem (By the way, this problem has multiple pages.) Tells me that I tried it on localhost or another server. I have paid for several years one server. I did not show any problema with any other CMS (Wordpress, Drupal, Joomla, PHP-Fusion ...).

Flame CMS I immediately liked and would like to use it as a CMS for my website server. We find common solutions?

**Comment by FailZorD** [comment]
Please take a picture of your installation and send it to me. Maybe you are installing something wrong, or take a Video as one of the guys over ACWEB did. And we could provide him with a fix.

**Comment by Vycraftujto** [comment]
Read properly what I write? I installed CMS being displayed. The only thing I did was I uploaded the files to FTP and opened in the browser pages. Errors that I mentioned have proved the opened page. Next, I did not get

**Comment by netcho** [comment]
Check your php.ini as your host might've changed the default settings which causes this error ;)

**Comment by tlcd96** [comment]
i will make an temporary patch, see if you are able to see it. (replace the index.php for the new index here)

**Comment by tlcd96** [comment]
the temp patch was made. check if it is corrected please
