### ISSUE TITLE
Website all blank

### ISSUE THREAD

**Issue by Swockale** [FlameNET/FlameCMS#12]
Hello.

I'd just installed the latest version on my website, http://wow-wrath.com/beta3
The issue is tho, I can only see text and not the template it self. Any reason to why this could be? The setup was successful. I am online at Skype: Swockale
##

**Comment by FailZorD** [comment]
As you install it, you must add the website link to the installation and it has to be correct. For example: 
http://wow-wrath.com/beta3/ (if you wanna test it in a folder)
If you wanna test it on a domain add the domain. For example: http://yourdomain.com/
