### ISSUE TITLE
[3] Problems with installation

### ISSUE THREAD

**Issue by bonny1992** [FlameNET/FlameCMS#16]
Well, during installation it gives me "ERR_TOO_MANY_REDIRECTS".
I tried disabling Cloudflare on my host, but no luck.

How can I fix that?

EDIT:
Ok, I managed to get this installed by manually editing my system/config.php file, but... nothing is working xD My login doesn't simply work, it says I "need to activate" my account.

Obviously there's a HUGE issue with url redirection, since everytime I click on login it brings me to myurl.com/login/myurl.com/login/myurl.com/login and so on.

For now, it's not worth installing it, but it's an interesting project!
##

**Comment by tlcd96** [comment]
can you send printscreen's? it's hard to tell what it is widout an example

**Comment by tlcd96** [comment]
or tell us in the steps of the install it gives the error, by that, we can be able to fix the problem

**Comment by tlcd96** [comment]
branch?

**Comment by bonny1992** [comment]
It's as simple as I wrote:
1) Go to http://mypage.com/ (where is located the CMS)
2) It redirects to http://mypage.com/install/
3) Then the browser gives the error

At this point the only thing I could do, is to force the install by manually editing the file system/config.php and renaming/deleting the install folder.

Then I go back to my root page (http://mypage.com) and then it works, until I click on a link, then it redirects me to (for example) http://mypage.com/page/login/mypage.com/page/login, and everytime I click on the link, the situation goes worse: http://mypage.com/page/login/mypage.com/page/login/mypage.com/page/login/mypage.com/page/login and so on (pardon me if I didn't use the page hierarcy correctly, but I can't try that at the moment).

The branch I needed was the 3.3.5 one, since I use a 3.3.5 TrinityCore.

If it's useful, I use a lighttpd webserver with FastCGI (but everything else works, from url rewriting to redirects).

If you need something else, just tell me.
And sorry for the late reply.

**Comment by bonny1992** [comment]
Ok, with latest revision, I am able to see the first install page, but when I click on "Install" it gives me 404.

But, if I write the url http://mypage.com/install/step-2.php, it works (telling me I don't have Apache installed, but it should work with either).

**Comment by tlcd96** [comment]
have you try with apache2?

**Comment by tlcd96** [comment]
one of the requirements it's apache

**Comment by tlcd96** [comment]
![captura de ecra 11](https://cloud.githubusercontent.com/assets/7103685/10138641/09cb3cee-65ef-11e5-9206-0eb97943f3f9.png)

**Comment by tlcd96** [comment]
http://stackoverflow.com/questions/27115464/how-to-convert-my-apache-htaccess-rewrite-rules-to-lighttpd
convert the .htaccess content to lighttpd 
go directly to step 3

**Comment by wolone** [comment]
![QQ截图20190914183609](https://user-images.githubusercontent.com/48593469/64906910-96c51580-d71e-11e9-91e7-4474c1a67453.png)
Excuse me, what's the matter?
my apache 2.4.39

**Comment by tlcd96** [comment]
@wolone sorry for the wait, i've addered a polyfill to the code. (also i don't have much time, i only am correcting errors)

**Comment by tlcd96** [comment]
@wolone also, that error, i i'm not mistaken, only ocurrs on the cgi enviorment

**Comment by wolone** [comment]
Maybe it's my server running environment. Indeed, I downloaded several similar cms, which are different from the problems in Chengdu. At present, none of them can work properly on my server. I'm sorry I didn't find the right CMS for me. This does not mean that your work is not excellent. Thank you




------------------ 原始邮件 ------------------
发件人: "Skull Writter"<notifications@github.com>; 
发送时间: 2019年9月16日(星期一) 上午8:46
收件人: "FlameNET/FlameCMS"<FlameCMS@noreply.github.com>; 
抄送: "王镭"<71954466@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [FlameNET/FlameCMS] [3] Problems with installation (#16)




@wolone also, that error, i i'm not mistaken, only ocurrs on the cgi enviorment

**Comment by tlcd96** [comment]
i hope that i've helped, ur welcome
