### ISSUE TITLE
Installer can't connect to DB

### ISSUE THREAD

**Issue by Deuzz** [FlameNET/FlameCMS#17]
Hey,
I just tried to install FlameCMS (6.x.x branch) but I always get the following error:
Failed to connect to MySQL: Access denied for user 'cms'@'localhost' (using password: YES)

I'm 100% sure that I'm using the correct password.
And the weird part is that if I try to connect to the DB with the cms user I can connect to it without any problems :/

**Comment by tlcd96** [comment]
Deuzz can you send an printscreen?
if not, see if the user can access the database
if you can't i will try to see what is happening (if the problem is with the CMS)

**Comment by tlcd96** [comment]
i will try all the install steps to see exactly what is the problem.

**Comment by tlcd96** [comment]
i've checked, and it must be your config on install... you can check it working here:
(it's in portuguese :S)
https://flamecms.exdemsys.tk/6.x.x/

**Comment by Deuzz** [comment]
http://puu.sh/kqSZs/b2158cfe3c.jpg - This is the settings page with MySQL user list (Blacked out the IP)
http://puu.sh/kqT4j/9a0153808e.png - This is what I get when using localhost as IP (and the correct password)
http://puu.sh/kqT5T/c43f67c9ff.jpg - And this is what I get when I use the IP address ..

**Comment by tlcd96** [comment]
try one thing, change temporary the password and see if works

**Comment by tlcd96** [comment]
are the ports from the router opened?

**Comment by Deuzz** [comment]
The password change did nothing -> still access denied.
All ports are opened

**Comment by tlcd96** [comment]
you can try also with 127.0.0.1(localhost IP)

**Comment by tlcd96** [comment]
ok wierd

**Comment by Deuzz** [comment]
127.0.0.1 gives me the same error

**Comment by tlcd96** [comment]
external ip it works but not locakhost?

**Comment by Deuzz** [comment]
If I use the external IP then it tells me "Host 'Server IP' is not allowed to access this server"

**Comment by tlcd96** [comment]
create + 1 account, with the same settings, but the domain it's localhost (mysql it's an pain in the ass, i've had that problem)

**Comment by tlcd96** [comment]
if you want an image to explain tell

**Comment by tlcd96** [comment]
the name it's the same only changes the localhost

**Comment by Deuzz** [comment]
Now I've "website@%" and "website@localhost" with the same password - and it's giving me the same error :/

**Comment by tlcd96** [comment]
thats wierd

**Comment by tlcd96** [comment]
do you have the website in the same machine?

**Comment by Deuzz** [comment]
Yea it's on the same server

**Comment by tlcd96** [comment]
ok, what it's your apache2/nginx/mysql config?

**Comment by tlcd96** [comment]
and versions

**Comment by tlcd96** [comment]
if you only have apache and mysql, tell me what is the config and the versions to see if i can do something to help you

**Comment by tlcd96** [comment]
if you don't know how to give that, tell me if your server is windows or linux based

**Comment by tlcd96** [comment]
or do you have team viewer?

**Comment by Deuzz** [comment]
Apache: Apache/2.4.12 (Win32) OpenSSL/1.0.1l PHP/5.6.8 Configs: http://puu.sh/kr7nK/cdf070422b.txt
MySQL: MySQL Community Server 5.5.19-log  Configs: http://puu.sh/kr7um/956d049f52.txt (Yea, I know there's 3308 as port and on the picture of the settings is 3307 BUT I used 3308 to connect)

Sorry.. took me some time to find that stuff

**Comment by tlcd96** [comment]
soo i see your server it's win32 based, and it does not appear to have on the config's any kind of errors.... do you have teamviewer?

**Comment by Deuzz** [comment]
On my computer, yes

**Comment by tlcd96** [comment]
do you mind if you gave me access to your pc? too se if i can help?

**Comment by tlcd96** [comment]
if you want an more private place to send the id and key: add me on facebook-> https://www.facebook.com/adomasalcore3

**Comment by Deuzz** [comment]
To be honest.. I don't think that there's a way to fix it without reinstalling the MySQL server :/

**Comment by tlcd96** [comment]
try: easyphp

**Comment by tlcd96** [comment]
http://www.easyphp.org/

**Comment by tlcd96** [comment]
if you reinstall

**Comment by tlcd96** [comment]
if you install easyphp install Xdebug (it's an module of easyphp) (easy to install)

**Comment by Deuzz** [comment]
So, I tried it with EasyPhp on my computer - set the root password to 12345 and it what  does it show? Right. Access denied for user root@localhost ........

**Comment by tlcd96** [comment]
seriously? O.o

**Comment by tlcd96** [comment]
thats new... can you give access to teamviewer?

**Comment by Deuzz** [comment]
Okay, got it working.. Somehow it looks like it doesn't work on another port than 3306 :/ but now I've the problem that it says that my account is not activated

**Comment by tlcd96** [comment]
have you created an account?

**Comment by tlcd96** [comment]
when you finish to create the account, go to you database, see the record, copy the activation key, go to the url: %yourhost%/account/confirm.php?passkey=%activationkey%

**Comment by tlcd96** [comment]
or, set null the activation key field on the new account record

**Comment by tlcd96** [comment]
![captura de ecra 5](https://cloud.githubusercontent.com/assets/7103685/10138393/cbd35382-65ed-11e5-8f42-3578fee0342f.png)

**Comment by Deuzz** [comment]
Thanks :3

**Comment by tlcd96** [comment]
you're welcome
