### ISSUE TITLE
Parse error: syntax error, unexpected ')' in C:\xampp\htdocs\system\config.php on line 1

### ISSUE THREAD

**Issue by Reck1501** [FlameNET/FlameCMS#19]
I get "Parse error: syntax error, unexpected ')' in C:\xampp\htdocs\system\config.php on line 2" after installing FlameCMS

**Comment by tlcd96** [comment]
in the normal install or the install test?

**Comment by tlcd96** [comment]
and the branch please...

**Comment by Reck1501** [comment]
I tried with both install & install_test, same error, fork 3.3.5a

**Comment by tlcd96** [comment]
ok, i will see it.. just a sec

**Comment by tlcd96** [comment]
do you have xdebug installed?
if yes, send an screen shot, if you don't copy the config file content ('don't forget to remove the db info... etc')

**Comment by Reck1501** [comment]
I don't, but I manually installed the CMS and it worked. The reason I get the error, is that when the installation writes to the config file, it removes $_SESSION from if(isset($_SESSION))

**Comment by tlcd96** [comment]
that is wierd, that never happened on the tests
