### ISSUE TITLE
[2] Installer Error [0$]

### ISSUE THREAD

**Issue by Orangs** [FlameNET/FlameCMS#2]
Cant install on another server.
but! I configured different host, no localhost. Any solutions how to fix it?

error code:
Trying to connect to database...
                                Failed to connect to MySQL: Access denied for user 'root'@'localhost' (using password: YES)

**Comment by FailZorD** [comment]
I am not sure if you can do double connections yet but i will have to check it out.

**Comment by Orangs** [comment]
my problem is like this....etc:
Server, where i want the FTP+domain = etc IP 1.1.1.1
Server,where i want Core(Server)+Database = etc IP 1.1.1.2

If you know how to fix, i will be very happy :)
(I think FlameCMS can be more better than fusioncms)

**Comment by FailZorD** [comment]
Right now there is no Fix. We will add this feature later on for double Connection!
I hope this will clarify some things :)
Don't forget to check the TODO file for features that work and that will work on the future, and ofcourse features that do not work yet. And ofcourse if you want you can add a bounty on our project :+1: 

Link: https://github.com/FlameNET/FlameCMS/blob/master/TODO.md
