### ISSUE TITLE
Installation issue with MySQL and extens

### ISSUE THREAD

**Issue by Caprini** [FlameNET/FlameCMS#20]
First, when I clic on next step in the second step, there is an error with the link, and there is no extension (thesite.com/install/step-3 and .PHP is not here)

Then, when I fill in the form,  I Obtain the errors that appears in the image.

¿Some one know the solution?
![screen flamecms](https://cloud.githubusercontent.com/assets/16973491/14838252/cd03252e-0c1f-11e6-8144-4d77bc1e1b52.png)

**Comment by Caprini** [comment]
Solved! Just changed hostname to "localhost" until use Ip Address.
But now i Can' t see styles on the web like the image: 
![wowmeryfail2](https://cloud.githubusercontent.com/assets/16973491/14838689/082e5d0e-0c24-11e6-94f8-ed942af10e9f.png)

**Comment by Caprini** [comment]
Solved! "BASE URL" Must finish with "/"

**Comment by Caprini** [comment]
Solved URL Problems, make sure your rewrite engine is ON, and your vhost config is correct to allow rewrite! :D

**Comment by tlcd96** [comment]
sorry for not answering in time... but i'm glad that you have fixed the issue.
