### ISSUE TITLE
FlameCMS bugtracker

### ISSUE THREAD

**Issue by 97wow** [FlameNET/FlameCMS#23]
![20170222021547](https://cloud.githubusercontent.com/assets/11026453/23181628/a6be5d88-f8b0-11e6-9f9f-f9926d8f2f11.png)

**Comment by adomasalcore3** [comment]
u know that is not ready for use right? but thks btw, will correct it now

**Comment by tlcd96** [comment]
what is the branch?

**Comment by tlcd96** [comment]
and wrong repo... it's the FlameCms-3

**Comment by tlcd96** [comment]
btw, 
https://github.com/FlameNET/FlameCms-3 (latest update (updated now))

also, the framework it's not ready for use

**Comment by tlcd96** [comment]
and the repo is in the pre_alpha, not in the alpha

**Comment by 97wow** [comment]
thank you very much.
let me try follow your updated.

**Comment by tlcd96** [comment]
Also Checkup the milestones:
https://waffle.io/FlameNET/FlameCms-3

**Comment by 97wow** [comment]
notworlk

**Comment by tlcd96** [comment]
told you....

**Comment by 97wow** [comment]
okey~~
