### ISSUE TITLE
CMS

### ISSUE THREAD

**Issue by zubairfazal** [FlameNET/FlameCMS#27]
Can this CMS be used for non WOW private servers? Or is it made specificially for WOW?

**Comment by tlcd96** [comment]
this one was specifically for Wow, but the group never thought of another possibilities on this group, but you never know. 

Right now, sometimes if there's a bug, and the people put an issue on that, as you may have seen, i correct it. 

- i don't know if in the future, if i may end the FlameCMS whole site, or if i create another one.
- i don't know, also, if i may be developing, with the rest of the group, other kinds of CMS...

If there's enough support, i may be putting my hands again in the FlameCMS, WOW server management.

And if there's enough support, i may develop a hole kind of a new CMS for all the contents, but i may leave the plugin/module system at your criteria

(your - the fans)

**Comment by zubairfazal** [comment]
> this one was specifically for Wow, but the group never thought of another possibilities on this group, but you never know.
> 
> Right now, sometimes if there's a bug, and the people put an issue on that, as you may have seen, i correct it.
> 
> * i don't know if in the future, if i may end the FlameCMS whole site, or if i create another one.
> * i don't know, also, if i may be developing, with the rest of the group, other kinds of CMS...
> 
> If there's enough support, i may be putting my hands again in the FlameCMS, WOW server management.
> 
> And if there's enough support, i may develop a hole kind of a new CMS for all the contents, but i may leave the plugin/module system at your criteria
> 
> (your - the fans)

what happened to aquaflame cms

**Comment by tlcd96** [comment]
@zubairfazal  as i know, most of the developers had a shortage in time, including me...
others, never replied or talked to me, as the ones that never did, i cannot speak for them
