### ISSUE TITLE
[3] Registrations [0$]

### ISSUE THREAD

**Issue by Abrek** [FlameNET/FlameCMS#3]
Hi.
If possible realise registration for trinity core 6.0.x ? 
SOAP or PHP, but need this for last rev of TC.
Tnx.

**Comment by FailZorD** [comment]
I guess Registrations for Trinity Core 6.x.x work but Login is not ready yet. Wait for Luiz reply to be sure.

**Comment by oneluiz** [comment]
the visual part of the account register now ready ... just need the code

**Comment by oneluiz** [comment]
Soon register page ...Soap

**Comment by oneluiz** [comment]
closes 19fdfc20eca9631d978713673e35854fed0e466a
